version: '3.8'

# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     networks:
#       - app_network
#     # environment:
#     env_file:
#       - .env
#     # Ensure backend binds to 0.0.0.0 (configured in its own Dockerfile/startup command)
#     ports: #temporary map port for testing /docs from swagger
#       - "8000:8000"  # Maps port 8000 on the host to port 8000 in the container

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app_network
    env_file:
      - .env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app_network
    ports:
      - "8501:8501"  # Optional for direct access
    # environment:
    #   - BACKEND_URL=http://backend:8000
    env_file:
      - .env
    depends_on:
      - backend

  # nginx:
  #   image: nginx:1.17
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "80:80"
  #   networks:
  #     - app_network
  #   depends_on:
  #     - backend
  #     - frontend
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - backend
      - frontend

networks:
  app_network:
    driver: bridge