jobs:
  build-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run backend tests with pytest
        run: |
          cd backend
          pytest tests --maxfail=2 --disable-warnings -q

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend container
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/backend:pr-${{ github.sha }} ./backend

      - name: Build frontend container
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/frontend:pr-${{ github.sha }} ./frontend

      - name: Build nginx container
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/nginx:pr-${{ github.sha }} ./nginx

      - name: Run container smoke tests
        run: |
          docker compose -f docker-compose.yml up -d
          sleep 5
          curl -f http://localhost || (echo "Backend not responding" && exit 1)
          curl -f http://localhost/api/health || (echo "Health check failed" && exit 1)
          docker compose down
